services:
  orchestrator:
    build:
      context: . 
    ports:
      - "9000:9000"
    environment:
      - REACT_APP_HOST_URL=http://orchestrator:9000
      - REACT_APP_HOME_URL=http://home:8200
      - REACT_APP_API_URL=http://tech-challenge:3000  
    networks:
      - app-network
    depends_on:
      - home  
      - tech-challenge

  home:
    build:
      context: ../home  
    ports:
      - "8200:8200"
    networks:
      - app-network

  tech-challenge:
    build:
      context: ../tech-challenge-2
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/tech-challenge
    networks:
      - app-network
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
